[tool.black]
line-length = 120
target_version = ['py38']

[tool.isort]
default_section = "THIRDPARTY"
known_first_party = [
    "importer",
]
known_standard_library = [
    "typing",
    "setuptools",
    "pkg_resources",
]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true
line_length = 110
use_parentheses = true
